apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-config
data:
  DB_HOST: "dev-bank-db.cijmikuiuvut.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "bankdb"
  REACT_APP_API_URL: http://backend-service:8080
